In [1]:
import pandas as pd
df3 = pd.read_csv("2023NashikWeather.csv")
df4 = pd.read_csv("2024nashikWeather.csv")
df5 = pd.read_csv("2025NashikWeather.csv")

C:\Users\rahul\anaconda3\Lib\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\rahul\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
import pandas as pd
df22 = pd.read_csv('2022NashikMandi.csv')
df33 = pd.read_csv('2023NashikMandi.csv')
df44 = pd.read_csv('2024NashikMandi.csv')

In [3]:
df22.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
0,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,07/04/2022,601,1230,950,23
1,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,08/04/2022,300,1215,900,23
2,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,09/04/2022,400,1251,850,23
3,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,16/04/2022,600,1126,950,23
4,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,20/04/2022,400,1313,1000,23

In [4]:
df22.tail()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
1136,Maharashtra,Nashik,Yeola,Onion,Other,FAQ,21/05/2022,70,1012,600,23
1137,Maharashtra,Nashik,Yeola,Onion,Other,FAQ,23/05/2022,125,1071,700,23
1138,Maharashtra,Nashik,Yeola,Onion,Other,FAQ,27/05/2022,100,1072,825,23
1139,Maharashtra,Nashik,Yeola,Onion,Red,FAQ,04/03/2022,200,1816,1400,23
1140,Maharashtra,Nashik,Yeola,Onion,Red,FAQ,05/03/2022,200,1650,1350,23

In [5]:
df44.head()

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
0,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,09/05/2024,800,1951,1500.0,23
1,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,10/05/2024,700,2002,1580.0,23
2,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,16/05/2024,603,2016,1500.0,23
3,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,22/05/2024,635,2035,1550.0,23
4,Maharashtra,Nashik,Chandvad,Onion,Other,FAQ,24/05/2024,700,1974,1500.0,23

In [6]:
df22 = df22.drop(['State','District','Commodity','Grade','Commodity_Code'],axis=1)

In [7]:
df33 = df33.drop(['State','District','Commodity','Grade','Commodity_Code'],axis=1)
df44 = df44.drop(['State','District','Commodity','Grade','Commodity_Code'],axis=1)

In [8]:
df22 = df22.sort_values(by='Arrival_Date')
df33 = df33.sort_values(by='Arrival_Date')
df44 = df44.sort_values(by='Arrival_Date')

In [9]:
df22

,Market,Variety,Arrival_Date,Min_Price,Max_Price,Modal_Price
320,Lasalgaon,Other,01/03/2022,1200,1952,1701
332,Lasalgaon,Red,01/03/2022,500,2101,1775
352,Lasalgaon(Niphad),Red,01/03/2022,700,1941,1700
443,Lasalgaon(Vinchur),Red,01/03/2022,500,2200,1750
512,Manmad,Red,01/03/2022,300,2060,1900
...,...,...,...,...,...,...
831,Pimpalgaon,Other,31/05/2022,300,1605,1070
892,Pimpalgaon Baswant(Saykheda),Other,31/05/2022,300,1252,925
928,Satana,Other,31/05/2022,100,1395,980
1001,Sinner,Other,31/05/2022,250,1160,950
1044,Umrane,Other,31/05/2022,700,1300,1000

In [10]:
df33

,Market,Variety,Arrival_Date,Min_Price,Max_Price,Modal_Price
494,Nasik,Other,01/04/2023,400,1050,700
505,Nasik,Pole,01/04/2023,300,751,601
115,Dindori,Other,01/05/2023,551,930,735
26,Chandvad,Other,02/05/2023,200,1025,570
82,Devala,Other,02/05/2023,100,1100,675
...,...,...,...,...,...,...
591,Pimpalgaon,Other,31/05/2023,225,1575,701
613,Pimpalgaon Baswant(Saykheda),Other,31/05/2023,200,885,625
671,Satana,Other,31/05/2023,100,1265,735
717,Sinner,Other,31/05/2023,100,791,550
768,Yeola,Other,31/05/2023,150,926,650

In [11]:
df44

,Market,Variety,Arrival_Date,Min_Price,Max_Price,Modal_Price
21,Chandvad,Red,01/03/2024,501,1667,1430.00
46,Chandvad,Other,01/03/2024,1100,1750,1600.00
100,Devala,Red,01/03/2024,250,1635,1525.00
154,Kalvan,Red,01/03/2024,700,1800,1300.00
194,Lasalgaon,Other,01/03/2024,586,1751,1650.00
...,...,...,...,...,...,...
698,Pimpalgaon Baswant(Saykheda),Other,31/05/2024,600,2070,1840.00
754,Satana,Other,31/05/2024,300,2300,2050.00
779,Shree Rameshwar Krushi Market,Other,31/05/2024,300,2361,1726.88
819,Sinner,Other,31/05/2024,300,2227,1950.00
852,Yeola,Other,31/05/2024,750,2080,1750.00

In [12]:
df22 = df22.rename(columns={'Arrival_Date': 'date'})

In [13]:
df33 = df33.rename(columns={'Arrival_Date': 'date'})

In [14]:
df44 = df44.rename(columns={'Arrival_Date': 'date'})

In [15]:
df33

,Market,Variety,date,Min_Price,Max_Price,Modal_Price
494,Nasik,Other,01/04/2023,400,1050,700
505,Nasik,Pole,01/04/2023,300,751,601
115,Dindori,Other,01/05/2023,551,930,735
26,Chandvad,Other,02/05/2023,200,1025,570
82,Devala,Other,02/05/2023,100,1100,675
...,...,...,...,...,...,...
591,Pimpalgaon,Other,31/05/2023,225,1575,701
613,Pimpalgaon Baswant(Saykheda),Other,31/05/2023,200,885,625
671,Satana,Other,31/05/2023,100,1265,735
717,Sinner,Other,31/05/2023,100,791,550
768,Yeola,Other,31/05/2023,150,926,650

In [16]:
from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()

df33['Market_encoded'] = encode.fit_transform(df33['Market'])
df33['Variety_encoded'] = encode.fit_transform(df33['Variety'])

In [17]:
df33 = df33.drop(['Market','Variety'],axis=1)

In [18]:
df33

,date,Min_Price,Max_Price,Modal_Price,Market_encoded,Variety_encoded
494,01/04/2023,400,1050,700,11,0
505,01/04/2023,300,751,601,11,1
115,01/05/2023,551,930,735,2,0
26,02/05/2023,200,1025,570,0,0
82,02/05/2023,100,1100,675,1,0
...,...,...,...,...,...,...
591,31/05/2023,225,1575,701,12,0
613,31/05/2023,200,885,625,13,0
671,31/05/2023,100,1265,735,14,0
717,31/05/2023,100,791,550,15,0
768,31/05/2023,150,926,650,17,0

In [19]:
df22

,Market,Variety,date,Min_Price,Max_Price,Modal_Price
320,Lasalgaon,Other,01/03/2022,1200,1952,1701
332,Lasalgaon,Red,01/03/2022,500,2101,1775
352,Lasalgaon(Niphad),Red,01/03/2022,700,1941,1700
443,Lasalgaon(Vinchur),Red,01/03/2022,500,2200,1750
512,Manmad,Red,01/03/2022,300,2060,1900
...,...,...,...,...,...,...
831,Pimpalgaon,Other,31/05/2022,300,1605,1070
892,Pimpalgaon Baswant(Saykheda),Other,31/05/2022,300,1252,925
928,Satana,Other,31/05/2022,100,1395,980
1001,Sinner,Other,31/05/2022,250,1160,950
1044,Umrane,Other,31/05/2022,700,1300,1000

In [20]:
from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()

df22['Market_encoded'] = encode.fit_transform(df22['Market'])
df22['Variety_encoded'] = encode.fit_transform(df22['Variety'])
df22 = df22.drop(['Market','Variety'],axis=1)

In [21]:
df22

,date,Min_Price,Max_Price,Modal_Price,Market_encoded,Variety_encoded
320,01/03/2022,1200,1952,1701,5,0
332,01/03/2022,500,2101,1775,5,2
352,01/03/2022,700,1941,1700,6,2
443,01/03/2022,500,2200,1750,7,2
512,01/03/2022,300,2060,1900,8,2
...,...,...,...,...,...,...
831,31/05/2022,300,1605,1070,12,0
892,31/05/2022,300,1252,925,13,0
928,31/05/2022,100,1395,980,14,0
1001,31/05/2022,250,1160,950,15,0
1044,31/05/2022,700,1300,1000,16,0

In [22]:
from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()

df44['Market_encoded'] = encode.fit_transform(df44['Market'])
df44['Variety_encoded'] = encode.fit_transform(df44['Variety'])
df44 = df44.drop(['Market','Variety'],axis=1)

In [23]:
df22 = df22.rename(columns={'Market_encoded':'Market','Variety_encoded':'Variety'})

In [24]:
df33 = df33.rename(columns={'Market_encoded':'Market','Variety_encoded':'Variety'})
df44 = df44.rename(columns={'Market_encoded':'Market','Variety_encoded':'Variety'})

In [25]:
df44

           date  Min_Price  Max_Price  Modal_Price  Market  Variety
21   01/03/2024        501       1667      1430.00       0        3
46   01/03/2024       1100       1750      1600.00       0        1
100  01/03/2024        250       1635      1525.00       1        3
154  01/03/2024        700       1800      1300.00       3        3
194  01/03/2024        586       1751      1650.00       4        1
..          ...        ...        ...          ...     ...      ...
698  31/05/2024        600       2070      1840.00      14        1
754  31/05/2024        300       2300      2050.00      15        1
779  31/05/2024        300       2361      1726.88      17        1
819  31/05/2024        300       2227      1950.00      18        1
852  31/05/2024        750       2080      1750.00      20        1

[892 rows x 6 columns]

In [26]:
df44.describe()

         Min_Price    Max_Price  Modal_Price      Market     Variety
count   892.000000   892.000000   892.000000  892.000000  892.000000
mean    598.778027  1763.178251  1507.222948    9.063901    1.559417
std     292.655561   281.130060   227.011298    5.907191    0.896339
min     100.000000  1201.000000   725.000000    0.000000    0.000000
25%     400.000000  1545.000000  1350.000000    4.000000    1.000000
50%     550.000000  1750.000000  1500.000000    9.000000    1.000000
75%     713.750000  1970.000000  1662.500000   13.000000    3.000000
max    2100.000000  2851.000000  2200.000000   20.000000    3.000000

In [27]:
df44.info()

<class 'pandas.DataFrame'>
Index: 892 entries, 21 to 852
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         892 non-null    str
 1   Min_Price    892 non-null    int64
 2   Max_Price    892 non-null    int64
 3   Modal_Price  892 non-null    float64
 4   Market       892 non-null    int32
 5   Variety      892 non-null    int32
dtypes: float64(1), int32(2), int64(2), str(1)
memory usage: 50.6 KB

In [28]:
df3

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,1.32,26.01,34.79,19.06,20.48,4.30,0.00,2.09,94.93,2023-03-01 00:00:00
1,1.72,26.51,35.02,18.02,24.38,5.17,0.00,2.69,95.00,2023-03-02 00:00:00
2,1.70,27.54,35.58,19.02,26.08,5.95,0.00,2.64,95.02,2023-03-03 00:00:00
3,1.27,28.45,35.86,21.57,26.05,6.31,0.00,2.09,95.00,2023-03-04 00:00:00
4,2.09,28.24,34.43,22.88,28.41,6.97,1.28,3.17,94.95,2023-03-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...
87,4.94,27.60,34.94,22.46,64.19,14.92,0.00,6.51,94.42,2023-05-27 00:00:00
88,4.08,28.41,35.80,23.12,61.49,14.85,0.00,5.36,94.34,2023-05-28 00:00:00
89,2.83,30.22,39.31,23.32,52.87,13.29,0.12,3.74,94.31,2023-05-29 00:00:00
90,2.76,30.77,38.53,22.83,43.51,11.34,0.03,3.74,94.31,2023-05-30 00:00:00
91,2.62,30.85,38.58,23.93,41.24,11.16,0.00,3.58,94.30,2023-05-31 00:00:00

In [29]:
df3.info()

<class 'pandas.DataFrame'>
RangeIndex: 92 entries, 0 to 91
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   WS2M         92 non-null     float64
 1   T2M          92 non-null     float64
 2   T2M_MAX      92 non-null     float64
 3   T2M_MIN      92 non-null     float64
 4   RH2M         92 non-null     float64
 5   QV2M         92 non-null     float64
 6   PRECTOTCORR  92 non-null     float64
 7   WS10M        92 non-null     float64
 8   PS           92 non-null     float64
 9   date         92 non-null     str
dtypes: float64(9), str(1)
memory usage: 9.0 KB

In [30]:
df3['date'] = pd.to_datetime(df3['date'])

In [31]:
df3

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,1.32,26.01,34.79,19.06,20.48,4.30,0.00,2.09,94.93,2023-03-01
1,1.72,26.51,35.02,18.02,24.38,5.17,0.00,2.69,95.00,2023-03-02
2,1.70,27.54,35.58,19.02,26.08,5.95,0.00,2.64,95.02,2023-03-03
3,1.27,28.45,35.86,21.57,26.05,6.31,0.00,2.09,95.00,2023-03-04
4,2.09,28.24,34.43,22.88,28.41,6.97,1.28,3.17,94.95,2023-03-05
...,...,...,...,...,...,...,...,...,...,...
87,4.94,27.60,34.94,22.46,64.19,14.92,0.00,6.51,94.42,2023-05-27
88,4.08,28.41,35.80,23.12,61.49,14.85,0.00,5.36,94.34,2023-05-28
89,2.83,30.22,39.31,23.32,52.87,13.29,0.12,3.74,94.31,2023-05-29
90,2.76,30.77,38.53,22.83,43.51,11.34,0.03,3.74,94.31,2023-05-30
91,2.62,30.85,38.58,23.93,41.24,11.16,0.00,3.58,94.30,2023-05-31

In [32]:
df22['date'] = pd.to_datetime(df22['date'], dayfirst=True)

In [33]:
df22

           date  Min_Price  Max_Price  Modal_Price  Market  Variety
320  2022-03-01       1200       1952         1701       5        0
332  2022-03-01        500       2101         1775       5        2
352  2022-03-01        700       1941         1700       6        2
443  2022-03-01        500       2200         1750       7        2
512  2022-03-01        300       2060         1900       8        2
...         ...        ...        ...          ...     ...      ...
831  2022-05-31        300       1605         1070      12        0
892  2022-05-31        300       1252          925      13        0
928  2022-05-31        100       1395          980      14        0
1001 2022-05-31        250       1160          950      15        0
1044 2022-05-31        700       1300         1000      16        0

[1141 rows x 6 columns]

In [34]:
df33['date'] = pd.to_datetime(df33['date'], dayfirst=True)
df44['date'] = pd.to_datetime(df44['date'], dayfirst=True)

In [35]:
df33 = df33.sort_values(by='date')
df22 = df22.sort_values(by='date')
df44 = df44.sort_values(by='date')

In [36]:
df33

          date  Min_Price  Max_Price  Modal_Price  Market  Variety
769 2023-03-31        100        601          400      17        2
55  2023-03-31        100        900          775       1        0
73  2023-03-31        100        825          625       1        2
86  2023-03-31        655        900          750       2        0
143 2023-03-31        650        950          801       3        0
..         ...        ...        ...          ...     ...      ...
103 2023-05-31        300       1025          650       2        0
65  2023-05-31        100        980          800       1        0
717 2023-05-31        100        791          550      15        0
337 2023-05-31        500       1240          825       7        0
768 2023-05-31        150        926          650      17        0

[781 rows x 6 columns]

In [37]:
df22

           date  Min_Price  Max_Price  Modal_Price  Market  Variety
320  2022-03-01       1200       1952         1701       5        0
332  2022-03-01        500       2101         1775       5        2
352  2022-03-01        700       1941         1700       6        2
443  2022-03-01        500       2200         1750       7        2
512  2022-03-01        300       2060         1900       8        2
...         ...        ...        ...          ...     ...      ...
117  2022-05-31        100       1275         1050       1        0
41   2022-05-31        700       1480          850       0        0
1001 2022-05-31        250       1160          950      15        0
466  2022-05-31        500       1411         1100       7        0
1044 2022-05-31        700       1300         1000      16        0

[1141 rows x 6 columns]

In [38]:
df44

          date  Min_Price  Max_Price  Modal_Price  Market  Variety
21  2024-03-01        501       1667       1430.0       0        3
885 2024-03-01        600       1800       1600.0      20        3
824 2024-03-01        701       1700       1450.0      19        3
736 2024-03-01        100       1695       1410.0      15        3
704 2024-03-01        400       1676       1375.0      14        3
..         ...        ...        ...          ...     ...      ...
92  2024-05-31        350       2175       1880.0       1        1
60  2024-05-31       1180       2321       1950.0       0        1
819 2024-05-31        300       2227       1950.0      18        1
465 2024-05-31        400       2050       1800.0       9        1
852 2024-05-31        750       2080       1750.0      20        1

[892 rows x 6 columns]

In [39]:
df33['date'].isna().sum()

0

In [40]:
#weather

In [41]:
df3

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,1.32,26.01,34.79,19.06,20.48,4.30,0.00,2.09,94.93,2023-03-01
1,1.72,26.51,35.02,18.02,24.38,5.17,0.00,2.69,95.00,2023-03-02
2,1.70,27.54,35.58,19.02,26.08,5.95,0.00,2.64,95.02,2023-03-03
3,1.27,28.45,35.86,21.57,26.05,6.31,0.00,2.09,95.00,2023-03-04
4,2.09,28.24,34.43,22.88,28.41,6.97,1.28,3.17,94.95,2023-03-05
...,...,...,...,...,...,...,...,...,...,...
87,4.94,27.60,34.94,22.46,64.19,14.92,0.00,6.51,94.42,2023-05-27
88,4.08,28.41,35.80,23.12,61.49,14.85,0.00,5.36,94.34,2023-05-28
89,2.83,30.22,39.31,23.32,52.87,13.29,0.12,3.74,94.31,2023-05-29
90,2.76,30.77,38.53,22.83,43.51,11.34,0.03,3.74,94.31,2023-05-30
91,2.62,30.85,38.58,23.93,41.24,11.16,0.00,3.58,94.30,2023-05-31

In [42]:
df4

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,2.13,29.03,35.20,23.42,33.86,8.65,0.04,3.05,94.65,2024-03-01 00:00:00
1,3.42,25.63,33.93,19.61,52.70,10.48,0.00,4.62,94.63,2024-03-02 00:00:00
2,3.88,21.40,28.60,14.72,58.56,9.46,0.01,5.33,94.67,2024-03-03 00:00:00
3,2.02,20.54,31.33,12.73,36.30,4.72,0.00,3.03,94.71,2024-03-04 00:00:00
4,2.42,22.48,34.93,12.42,14.04,2.29,0.00,3.68,94.65,2024-03-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...
87,5.27,29.52,37.12,24.73,61.04,15.66,0.00,6.97,93.85,2024-05-27 00:00:00
88,5.90,29.88,38.28,24.42,61.96,16.21,0.00,7.81,93.85,2024-05-28 00:00:00
89,5.54,29.61,37.66,24.64,65.12,17.04,0.01,7.32,93.88,2024-05-29 00:00:00
90,4.77,30.03,37.77,24.89,63.66,16.94,0.01,6.25,93.99,2024-05-30 00:00:00
91,4.09,30.14,38.50,23.90,59.60,15.63,0.00,5.35,94.07,2024-05-31 00:00:00

In [43]:
df5

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,2.04,27.41,36.52,20.18,29.32,6.61,0.00,3.08,94.58,2025-03-01 00:00:00
1,2.29,26.52,36.74,18.32,29.18,6.04,0.00,3.52,94.53,2025-03-02 00:00:00
2,2.74,26.72,36.59,18.41,28.97,6.00,0.00,4.12,94.60,2025-03-03 00:00:00
3,2.82,25.56,35.03,18.82,26.80,5.48,0.00,4.24,94.68,2025-03-04 00:00:00
4,2.97,24.00,35.15,15.11,14.06,2.37,0.00,4.50,94.69,2025-03-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...
87,3.34,25.57,28.52,24.07,88.30,19.32,24.32,4.50,93.70,2025-05-27 00:00:00
88,3.92,25.60,29.20,23.59,84.85,18.51,7.78,5.26,93.72,2025-05-28 00:00:00
89,4.20,25.71,29.56,23.23,85.44,18.79,6.86,5.65,93.60,2025-05-29 00:00:00
90,4.61,26.11,29.93,23.93,84.03,18.85,0.00,6.21,93.65,2025-05-30 00:00:00
91,4.98,26.05,30.64,23.37,82.03,18.18,0.24,6.71,94.00,2025-05-31 00:00:00

In [44]:
df2 = pd.read_csv("2022NashikWeather.csv")

In [45]:
df2.rename(columns={
    'YEAR': 'year',
    'MO': 'month',
    'DY': 'day'
}, inplace=True)

In [46]:
df2['date'] = pd.to_datetime(df2[['year','month','day']])

In [47]:
df2 = df2.drop(['year','month','day'],axis=1)

In [48]:
df2

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,1.56,25.25,34.67,16.65,22.69,4.44,0.00,2.66,94.70,2022-03-01
1,2.04,25.80,34.92,17.68,25.65,5.35,0.00,3.17,94.65,2022-03-02
2,2.39,26.27,34.73,18.49,24.70,5.26,0.00,3.54,94.64,2022-03-03
3,2.24,26.14,34.85,18.79,23.21,4.88,0.00,3.31,94.68,2022-03-04
4,1.73,26.32,35.63,18.03,22.49,4.90,0.00,2.71,94.59,2022-03-05
...,...,...,...,...,...,...,...,...,...,...
87,5.12,27.34,34.14,22.64,66.45,15.30,0.00,6.78,94.18,2022-05-27
88,5.14,27.78,34.78,22.97,66.21,15.62,0.00,6.80,94.10,2022-05-28
89,5.24,27.53,34.29,23.07,66.42,15.53,0.00,6.94,94.10,2022-05-29
90,4.81,27.99,35.30,22.75,64.33,15.39,0.00,6.34,94.06,2022-05-30
91,4.48,28.48,36.24,23.13,61.64,14.87,0.01,5.86,93.99,2022-05-31

In [49]:
df3

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,1.32,26.01,34.79,19.06,20.48,4.30,0.00,2.09,94.93,2023-03-01
1,1.72,26.51,35.02,18.02,24.38,5.17,0.00,2.69,95.00,2023-03-02
2,1.70,27.54,35.58,19.02,26.08,5.95,0.00,2.64,95.02,2023-03-03
3,1.27,28.45,35.86,21.57,26.05,6.31,0.00,2.09,95.00,2023-03-04
4,2.09,28.24,34.43,22.88,28.41,6.97,1.28,3.17,94.95,2023-03-05
...,...,...,...,...,...,...,...,...,...,...
87,4.94,27.60,34.94,22.46,64.19,14.92,0.00,6.51,94.42,2023-05-27
88,4.08,28.41,35.80,23.12,61.49,14.85,0.00,5.36,94.34,2023-05-28
89,2.83,30.22,39.31,23.32,52.87,13.29,0.12,3.74,94.31,2023-05-29
90,2.76,30.77,38.53,22.83,43.51,11.34,0.03,3.74,94.31,2023-05-30
91,2.62,30.85,38.58,23.93,41.24,11.16,0.00,3.58,94.30,2023-05-31

In [50]:
df4

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,2.13,29.03,35.20,23.42,33.86,8.65,0.04,3.05,94.65,2024-03-01 00:00:00
1,3.42,25.63,33.93,19.61,52.70,10.48,0.00,4.62,94.63,2024-03-02 00:00:00
2,3.88,21.40,28.60,14.72,58.56,9.46,0.01,5.33,94.67,2024-03-03 00:00:00
3,2.02,20.54,31.33,12.73,36.30,4.72,0.00,3.03,94.71,2024-03-04 00:00:00
4,2.42,22.48,34.93,12.42,14.04,2.29,0.00,3.68,94.65,2024-03-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...
87,5.27,29.52,37.12,24.73,61.04,15.66,0.00,6.97,93.85,2024-05-27 00:00:00
88,5.90,29.88,38.28,24.42,61.96,16.21,0.00,7.81,93.85,2024-05-28 00:00:00
89,5.54,29.61,37.66,24.64,65.12,17.04,0.01,7.32,93.88,2024-05-29 00:00:00
90,4.77,30.03,37.77,24.89,63.66,16.94,0.01,6.25,93.99,2024-05-30 00:00:00
91,4.09,30.14,38.50,23.90,59.60,15.63,0.00,5.35,94.07,2024-05-31 00:00:00

In [51]:
df4['date'] = pd.to_datetime(df4['date'])

In [52]:
df4

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,2.13,29.03,35.20,23.42,33.86,8.65,0.04,3.05,94.65,2024-03-01
1,3.42,25.63,33.93,19.61,52.70,10.48,0.00,4.62,94.63,2024-03-02
2,3.88,21.40,28.60,14.72,58.56,9.46,0.01,5.33,94.67,2024-03-03
3,2.02,20.54,31.33,12.73,36.30,4.72,0.00,3.03,94.71,2024-03-04
4,2.42,22.48,34.93,12.42,14.04,2.29,0.00,3.68,94.65,2024-03-05
...,...,...,...,...,...,...,...,...,...,...
87,5.27,29.52,37.12,24.73,61.04,15.66,0.00,6.97,93.85,2024-05-27
88,5.90,29.88,38.28,24.42,61.96,16.21,0.00,7.81,93.85,2024-05-28
89,5.54,29.61,37.66,24.64,65.12,17.04,0.01,7.32,93.88,2024-05-29
90,4.77,30.03,37.77,24.89,63.66,16.94,0.01,6.25,93.99,2024-05-30
91,4.09,30.14,38.50,23.90,59.60,15.63,0.00,5.35,94.07,2024-05-31

In [53]:
#lets check all data sets

In [54]:
df22

           date  Min_Price  Max_Price  Modal_Price  Market  Variety
320  2022-03-01       1200       1952         1701       5        0
332  2022-03-01        500       2101         1775       5        2
352  2022-03-01        700       1941         1700       6        2
443  2022-03-01        500       2200         1750       7        2
512  2022-03-01        300       2060         1900       8        2
...         ...        ...        ...          ...     ...      ...
117  2022-05-31        100       1275         1050       1        0
41   2022-05-31        700       1480          850       0        0
1001 2022-05-31        250       1160          950      15        0
466  2022-05-31        500       1411         1100       7        0
1044 2022-05-31        700       1300         1000      16        0

[1141 rows x 6 columns]

In [55]:
df33

          date  Min_Price  Max_Price  Modal_Price  Market  Variety
769 2023-03-31        100        601          400      17        2
55  2023-03-31        100        900          775       1        0
73  2023-03-31        100        825          625       1        2
86  2023-03-31        655        900          750       2        0
143 2023-03-31        650        950          801       3        0
..         ...        ...        ...          ...     ...      ...
103 2023-05-31        300       1025          650       2        0
65  2023-05-31        100        980          800       1        0
717 2023-05-31        100        791          550      15        0
337 2023-05-31        500       1240          825       7        0
768 2023-05-31        150        926          650      17        0

[781 rows x 6 columns]

In [56]:
df44

          date  Min_Price  Max_Price  Modal_Price  Market  Variety
21  2024-03-01        501       1667       1430.0       0        3
885 2024-03-01        600       1800       1600.0      20        3
824 2024-03-01        701       1700       1450.0      19        3
736 2024-03-01        100       1695       1410.0      15        3
704 2024-03-01        400       1676       1375.0      14        3
..         ...        ...        ...          ...     ...      ...
92  2024-05-31        350       2175       1880.0       1        1
60  2024-05-31       1180       2321       1950.0       0        1
819 2024-05-31        300       2227       1950.0      18        1
465 2024-05-31        400       2050       1800.0       9        1
852 2024-05-31        750       2080       1750.0      20        1

[892 rows x 6 columns]

In [57]:
df2

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,1.56,25.25,34.67,16.65,22.69,4.44,0.00,2.66,94.70,2022-03-01
1,2.04,25.80,34.92,17.68,25.65,5.35,0.00,3.17,94.65,2022-03-02
2,2.39,26.27,34.73,18.49,24.70,5.26,0.00,3.54,94.64,2022-03-03
3,2.24,26.14,34.85,18.79,23.21,4.88,0.00,3.31,94.68,2022-03-04
4,1.73,26.32,35.63,18.03,22.49,4.90,0.00,2.71,94.59,2022-03-05
...,...,...,...,...,...,...,...,...,...,...
87,5.12,27.34,34.14,22.64,66.45,15.30,0.00,6.78,94.18,2022-05-27
88,5.14,27.78,34.78,22.97,66.21,15.62,0.00,6.80,94.10,2022-05-28
89,5.24,27.53,34.29,23.07,66.42,15.53,0.00,6.94,94.10,2022-05-29
90,4.81,27.99,35.30,22.75,64.33,15.39,0.00,6.34,94.06,2022-05-30
91,4.48,28.48,36.24,23.13,61.64,14.87,0.01,5.86,93.99,2022-05-31

In [58]:
df3

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,1.32,26.01,34.79,19.06,20.48,4.30,0.00,2.09,94.93,2023-03-01
1,1.72,26.51,35.02,18.02,24.38,5.17,0.00,2.69,95.00,2023-03-02
2,1.70,27.54,35.58,19.02,26.08,5.95,0.00,2.64,95.02,2023-03-03
3,1.27,28.45,35.86,21.57,26.05,6.31,0.00,2.09,95.00,2023-03-04
4,2.09,28.24,34.43,22.88,28.41,6.97,1.28,3.17,94.95,2023-03-05
...,...,...,...,...,...,...,...,...,...,...
87,4.94,27.60,34.94,22.46,64.19,14.92,0.00,6.51,94.42,2023-05-27
88,4.08,28.41,35.80,23.12,61.49,14.85,0.00,5.36,94.34,2023-05-28
89,2.83,30.22,39.31,23.32,52.87,13.29,0.12,3.74,94.31,2023-05-29
90,2.76,30.77,38.53,22.83,43.51,11.34,0.03,3.74,94.31,2023-05-30
91,2.62,30.85,38.58,23.93,41.24,11.16,0.00,3.58,94.30,2023-05-31

In [59]:
df4

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,2.13,29.03,35.20,23.42,33.86,8.65,0.04,3.05,94.65,2024-03-01
1,3.42,25.63,33.93,19.61,52.70,10.48,0.00,4.62,94.63,2024-03-02
2,3.88,21.40,28.60,14.72,58.56,9.46,0.01,5.33,94.67,2024-03-03
3,2.02,20.54,31.33,12.73,36.30,4.72,0.00,3.03,94.71,2024-03-04
4,2.42,22.48,34.93,12.42,14.04,2.29,0.00,3.68,94.65,2024-03-05
...,...,...,...,...,...,...,...,...,...,...
87,5.27,29.52,37.12,24.73,61.04,15.66,0.00,6.97,93.85,2024-05-27
88,5.90,29.88,38.28,24.42,61.96,16.21,0.00,7.81,93.85,2024-05-28
89,5.54,29.61,37.66,24.64,65.12,17.04,0.01,7.32,93.88,2024-05-29
90,4.77,30.03,37.77,24.89,63.66,16.94,0.01,6.25,93.99,2024-05-30
91,4.09,30.14,38.50,23.90,59.60,15.63,0.00,5.35,94.07,2024-05-31

In [60]:
#merging

In [61]:
DF2 = pd.merge(df22, df2, on='date', how='left')
DF3 = pd.merge(df33, df3, on='date', how='left')
DF4 = pd.merge(df44, df4, on='date', how='left')

In [62]:
DF2

,date,Min_Price,Max_Price,Modal_Price,Market,Variety,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS
0,2022-03-01,1200,1952,1701,5,0,1.56,25.25,34.67,16.65,22.69,4.44,0.00,2.66,94.70
1,2022-03-01,500,2101,1775,5,2,1.56,25.25,34.67,16.65,22.69,4.44,0.00,2.66,94.70
2,2022-03-01,700,1941,1700,6,2,1.56,25.25,34.67,16.65,22.69,4.44,0.00,2.66,94.70
3,2022-03-01,500,2200,1750,7,2,1.56,25.25,34.67,16.65,22.69,4.44,0.00,2.66,94.70
4,2022-03-01,300,2060,1900,8,2,1.56,25.25,34.67,16.65,22.69,4.44,0.00,2.66,94.70
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1136,2022-05-31,100,1275,1050,1,0,4.48,28.48,36.24,23.13,61.64,14.87,0.01,5.86,93.99
1137,2022-05-31,700,1480,850,0,0,4.48,28.48,36.24,23.13,61.64,14.87,0.01,5.86,93.99
1138,2022-05-31,250,1160,950,15,0,4.48,28.48,36.24,23.13,61.64,14.87,0.01,5.86,93.99
1139,2022-05-31,500,1411,1100,7,0,4.48,28.48,36.24,23.13,61.64,14.87,0.01,5.86,93.99
1140,2022-05-31,700,1300,1000,16,0,4.48,28.48,36.24,23.13,61.64,14.87,0.01,5.86,93.99

In [63]:
DF3

,date,Min_Price,Max_Price,Modal_Price,Market,Variety,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS
0,2023-03-31,100,601,400,17,2,3.25,23.63,32.00,17.32,51.57,8.80,0.0,4.47,94.39
1,2023-03-31,100,900,775,1,0,3.25,23.63,32.00,17.32,51.57,8.80,0.0,4.47,94.39
2,2023-03-31,100,825,625,1,2,3.25,23.63,32.00,17.32,51.57,8.80,0.0,4.47,94.39
3,2023-03-31,655,900,750,2,0,3.25,23.63,32.00,17.32,51.57,8.80,0.0,4.47,94.39
4,2023-03-31,650,950,801,3,0,3.25,23.63,32.00,17.32,51.57,8.80,0.0,4.47,94.39
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
776,2023-05-31,300,1025,650,2,0,2.62,30.85,38.58,23.93,41.24,11.16,0.0,3.58,94.30
777,2023-05-31,100,980,800,1,0,2.62,30.85,38.58,23.93,41.24,11.16,0.0,3.58,94.30
778,2023-05-31,100,791,550,15,0,2.62,30.85,38.58,23.93,41.24,11.16,0.0,3.58,94.30
779,2023-05-31,500,1240,825,7,0,2.62,30.85,38.58,23.93,41.24,11.16,0.0,3.58,94.30
780,2023-05-31,150,926,650,17,0,2.62,30.85,38.58,23.93,41.24,11.16,0.0,3.58,94.30

In [64]:
DF4

,date,Min_Price,Max_Price,Modal_Price,Market,Variety,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS
0,2024-03-01,501,1667,1430.0,0,3,2.13,29.03,35.2,23.42,33.86,8.65,0.04,3.05,94.65
1,2024-03-01,600,1800,1600.0,20,3,2.13,29.03,35.2,23.42,33.86,8.65,0.04,3.05,94.65
2,2024-03-01,701,1700,1450.0,19,3,2.13,29.03,35.2,23.42,33.86,8.65,0.04,3.05,94.65
3,2024-03-01,100,1695,1410.0,15,3,2.13,29.03,35.2,23.42,33.86,8.65,0.04,3.05,94.65
4,2024-03-01,400,1676,1375.0,14,3,2.13,29.03,35.2,23.42,33.86,8.65,0.04,3.05,94.65
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,2024-05-31,350,2175,1880.0,1,1,4.09,30.14,38.5,23.90,59.60,15.63,0.00,5.35,94.07
888,2024-05-31,1180,2321,1950.0,0,1,4.09,30.14,38.5,23.90,59.60,15.63,0.00,5.35,94.07
889,2024-05-31,300,2227,1950.0,18,1,4.09,30.14,38.5,23.90,59.60,15.63,0.00,5.35,94.07
890,2024-05-31,400,2050,1800.0,9,1,4.09,30.14,38.5,23.90,59.60,15.63,0.00,5.35,94.07
891,2024-05-31,750,2080,1750.0,20,1,4.09,30.14,38.5,23.90,59.60,15.63,0.00,5.35,94.07

In [65]:
DF2.to_excel('2022NashikMandiWeather.xlsx', index=False)
DF3.to_excel('2023NashikMandiWeather.xlsx', index=False)
DF4.to_excel('2024NashikMandiWeather.xlsx', index=False)

In [66]:
DF2.to_csv('2022NashikMandiWeather.csv', index=False)
DF3.to_csv('2023NashikMandiWeather.csv', index=False)
DF4.to_csv('2024NashikMandiWeather.csv', index=False)

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,2.04,27.41,36.52,20.18,29.32,6.61,0.00,3.08,94.58,2025-03-01 00:00:00
1,2.29,26.52,36.74,18.32,29.18,6.04,0.00,3.52,94.53,2025-03-02 00:00:00
2,2.74,26.72,36.59,18.41,28.97,6.00,0.00,4.12,94.60,2025-03-03 00:00:00
3,2.82,25.56,35.03,18.82,26.80,5.48,0.00,4.24,94.68,2025-03-04 00:00:00
4,2.97,24.00,35.15,15.11,14.06,2.37,0.00,4.50,94.69,2025-03-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...
87,3.34,25.57,28.52,24.07,88.30,19.32,24.32,4.50,93.70,2025-05-27 00:00:00
88,3.92,25.60,29.20,23.59,84.85,18.51,7.78,5.26,93.72,2025-05-28 00:00:00
89,4.20,25.71,29.56,23.23,85.44,18.79,6.86,5.65,93.60,2025-05-29 00:00:00
90,4.61,26.11,29.93,23.93,84.03,18.85,0.00,6.21,93.65,2025-05-30 00:00:00
91,4.98,26.05,30.64,23.37,82.03,18.18,0.24,6.71,94.00,2025-05-31 00:00:00

In [69]:
df55=pd.read_csv("2025NashikMandi.csv")

In [70]:
df55

,State,District,Market,Commodity,Variety,Grade,Arrival_Date,Min_Price,Max_Price,Modal_Price,Commodity_Code
0,Maharashtra,Nashik,Chandvad,Onion,Red,Local,22/03/2025,711.0,1416,1230.0,23
1,Maharashtra,Nashik,Chandvad,Onion,Red,Local,08/03/2025,1301.0,2033,1700.0,23
2,Maharashtra,Nashik,Chandvad,Onion,Red,Local,19/03/2025,625.0,1616,1460.0,23
3,Maharashtra,Nashik,Chandvad,Onion,Red,Local,10/03/2025,700.0,1750,1550.0,23
4,Maharashtra,Nashik,Chandvad,Onion,Red,Local,26/03/2025,1370.0,1600,1540.0,23
...,...,...,...,...,...,...,...,...,...,...,...
1458,Maharashtra,Nashik,Yeola,Onion,Other,Local,19/05/2025,50.0,1170,750.0,23
1459,Maharashtra,Nashik,Yeola,Onion,Other,Local,23/05/2025,101.0,1325,800.0,23
1460,Maharashtra,Nashik,Yeola,Onion,Other,Local,03/04/2025,500.0,1290,1150.0,23
1461,Maharashtra,Nashik,Yeola,Onion,Other,Local,04/04/2025,500.0,1319,1175.0,23
1462,Maharashtra,Nashik,Yeola,Onion,Other,Local,21/04/2025,300.0,1313,1000.0,23

In [71]:
#drop irrelevant columns
df55 = df55.drop(['State','District','Commodity','Grade','Commodity_Code'],axis=1)

In [73]:
df55 = df55.sort_values(by='Arrival_Date')

In [74]:
df55 = df55.rename(columns={'Arrival_Date': 'date'})

In [75]:
from sklearn.preprocessing import LabelEncoder

encode = LabelEncoder()

df55['Market_encoded'] = encode.fit_transform(df55['Market'])
df55['Variety_encoded'] = encode.fit_transform(df55['Variety'])

In [76]:
df55 = df55.drop(['Market','Variety'],axis=1)

In [77]:
df55

,date,Min_Price,Max_Price,Modal_Price,Market_encoded,Variety_encoded
213,01/03/2025,1701.0,3001,2375.0,3,2
331,01/03/2025,900.0,2476,2270.0,5,2
351,01/03/2025,1800.0,2441,2300.0,5,0
378,01/03/2025,1100.0,3101,2300.0,6,2
432,01/03/2025,1900.0,2400,2250.0,6,0
...,...,...,...,...,...,...
1013,31/05/2025,650.0,2251,1450.0,14,0
1109,31/05/2025,600.0,1411,1100.0,15,0
1157,31/05/2025,600.0,1400,1100.0,15,0
1277,31/05/2025,1150.0,2105,1250.0,17,0
1422,31/05/2025,150.0,1500,1100.0,21,0

In [78]:
df55 = df55.rename(columns={'Market_encoded':'Market','Variety_encoded':'Variety'})

In [79]:
df55['date'] = pd.to_datetime(df55['date'], dayfirst=True)

In [80]:
df55

           date  Min_Price  Max_Price  Modal_Price  Market  Variety
213  2025-03-01     1701.0       3001       2375.0       3        2
331  2025-03-01      900.0       2476       2270.0       5        2
351  2025-03-01     1800.0       2441       2300.0       5        0
378  2025-03-01     1100.0       3101       2300.0       6        2
432  2025-03-01     1900.0       2400       2250.0       6        0
...         ...        ...        ...          ...     ...      ...
1013 2025-05-31      650.0       2251       1450.0      14        0
1109 2025-05-31      600.0       1411       1100.0      15        0
1157 2025-05-31      600.0       1400       1100.0      15        0
1277 2025-05-31     1150.0       2105       1250.0      17        0
1422 2025-05-31      150.0       1500       1100.0      21        0

[1463 rows x 6 columns]

In [81]:
df5

,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS,date
0,2.04,27.41,36.52,20.18,29.32,6.61,0.00,3.08,94.58,2025-03-01 00:00:00
1,2.29,26.52,36.74,18.32,29.18,6.04,0.00,3.52,94.53,2025-03-02 00:00:00
2,2.74,26.72,36.59,18.41,28.97,6.00,0.00,4.12,94.60,2025-03-03 00:00:00
3,2.82,25.56,35.03,18.82,26.80,5.48,0.00,4.24,94.68,2025-03-04 00:00:00
4,2.97,24.00,35.15,15.11,14.06,2.37,0.00,4.50,94.69,2025-03-05 00:00:00
...,...,...,...,...,...,...,...,...,...,...
87,3.34,25.57,28.52,24.07,88.30,19.32,24.32,4.50,93.70,2025-05-27 00:00:00
88,3.92,25.60,29.20,23.59,84.85,18.51,7.78,5.26,93.72,2025-05-28 00:00:00
89,4.20,25.71,29.56,23.23,85.44,18.79,6.86,5.65,93.60,2025-05-29 00:00:00
90,4.61,26.11,29.93,23.93,84.03,18.85,0.00,6.21,93.65,2025-05-30 00:00:00
91,4.98,26.05,30.64,23.37,82.03,18.18,0.24,6.71,94.00,2025-05-31 00:00:00

In [83]:
df5['date'] = pd.to_datetime(df5['date'])

In [84]:
DF5 = pd.merge(df55, df5, on='date', how='left')

In [85]:
DF5

,date,Min_Price,Max_Price,Modal_Price,Market,Variety,WS2M,T2M,T2M_MAX,T2M_MIN,RH2M,QV2M,PRECTOTCORR,WS10M,PS
0,2025-03-01,1701.0,3001,2375.0,3,2,2.04,27.41,36.52,20.18,29.32,6.61,0.00,3.08,94.58
1,2025-03-01,900.0,2476,2270.0,5,2,2.04,27.41,36.52,20.18,29.32,6.61,0.00,3.08,94.58
2,2025-03-01,1800.0,2441,2300.0,5,0,2.04,27.41,36.52,20.18,29.32,6.61,0.00,3.08,94.58
3,2025-03-01,1100.0,3101,2300.0,6,2,2.04,27.41,36.52,20.18,29.32,6.61,0.00,3.08,94.58
4,2025-03-01,1900.0,2400,2250.0,6,0,2.04,27.41,36.52,20.18,29.32,6.61,0.00,3.08,94.58
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1458,2025-05-31,650.0,2251,1450.0,14,0,4.98,26.05,30.64,23.37,82.03,18.18,0.24,6.71,94.00
1459,2025-05-31,600.0,1411,1100.0,15,0,4.98,26.05,30.64,23.37,82.03,18.18,0.24,6.71,94.00
1460,2025-05-31,600.0,1400,1100.0,15,0,4.98,26.05,30.64,23.37,82.03,18.18,0.24,6.71,94.00
1461,2025-05-31,1150.0,2105,1250.0,17,0,4.98,26.05,30.64,23.37,82.03,18.18,0.24,6.71,94.00
1462,2025-05-31,150.0,1500,1100.0,21,0,4.98,26.05,30.64,23.37,82.03,18.18,0.24,6.71,94.00

In [87]:
DF5.to_csv('2025NashikMandiWeather.csv', index=False)